bazinga_faker:
    orm: doctrine
    entities:
        App\Entity\User:
            number: 3
            custom_formatters:
                Slug:   { method: }
        App\Entity\Category:
            number: 5
        App\Entity\Article:
            number: 15
